package liiga;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.08 14:19:53 // Generated by ComTest
 *
 */
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testToString72 */
  @Test
  public void testToString72() {    // Joukkue: 72
    Joukkue jouk = new Joukkue(); 
    jouk.parse("   3  |  Jyväskylä   | 1962"); 
    assertEquals("From: Joukkue line: 75", true, jouk.toString().startsWith("3|Jyväskylä|1962|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi147 */
  @Test
  public void testRekisteroi147() {    // Joukkue: 147
    Joukkue joukkue1 = new Joukkue(); 
    assertEquals("From: Joukkue line: 149", 0, joukkue1.getJoukkuenumero()); 
    joukkue1.rekisteroi(); 
    Joukkue joukkue2 = new Joukkue(); 
    joukkue2.rekisteroi(); 
    int j1 = joukkue1.getJoukkuenumero(); 
    int j2 = joukkue2.getJoukkuenumero(); 
    assertEquals("From: Joukkue line: 155", j2-1, j1); 
  } // Generated by ComTest END
}