package liiga;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.08 14:20:29 // Generated by ComTest
 *
 */
public class LiigaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa105 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa105() throws SailoException {    // Liiga: 105
    Liiga liiga = new Liiga(); 
    Pelaaja pelaaja1 = new Pelaaja(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja1.rekisteroi(); 
    pelaaja2.rekisteroi(); 
    assertEquals("From: Liiga line: 112", 0, liiga.getPelaajia()); 
    liiga.lisaa(pelaaja1); assertEquals("From: Liiga line: 113", 1, liiga.getPelaajia()); 
    liiga.lisaa(pelaaja2); assertEquals("From: Liiga line: 114", 2, liiga.getPelaajia()); 
    liiga.lisaa(pelaaja1); assertEquals("From: Liiga line: 115", 3, liiga.getPelaajia()); 
    assertEquals("From: Liiga line: 116", 3, liiga.getPelaajia()); 
    assertEquals("From: Liiga line: 117", pelaaja1, liiga.annaPelaaja(0)); 
    assertEquals("From: Liiga line: 118", pelaaja2, liiga.annaPelaaja(1)); 
    assertEquals("From: Liiga line: 119", pelaaja1, liiga.annaPelaaja(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa204 
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa204() throws SailoException {    // Liiga: 204
    Liiga liiga = new Liiga (); 
    Pelaaja eki = new Pelaaja(); eki.vastaaErikPerrin(); eki.rekisteroi(); 
    Pelaaja aki = new Pelaaja(); aki.vastaaErikPerrin(); aki.rekisteroi(); 
    liiga.lisaa(eki); 
    assertEquals("From: Liiga line: 210", 1, liiga.getPelaajia()); 
    liiga.korvaaTaiLisaa(aki); 
    assertEquals("From: Liiga line: 212", 2, liiga.getPelaajia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista229 
   * @throws Exception when error
   */
  @Test
  public void testPoista229() throws Exception {    // Liiga: 229
    Liiga liiga = new Liiga(); 
    Pelaaja eki = new Pelaaja(); eki.vastaaErikPerrin(); eki.rekisteroi(); 
    Pelaaja aki = new Pelaaja(); aki.vastaaErikPerrin(); aki.rekisteroi(); 
    liiga.lisaa(eki); 
    liiga.lisaa(aki); 
    assertEquals("From: Liiga line: 237", 2, liiga.getPelaajia()); 
    liiga.poista(eki); 
    assertEquals("From: Liiga line: 239", 1, liiga.getPelaajia()); 
    liiga.poista(aki); 
    assertEquals("From: Liiga line: 241", 0, liiga.getPelaajia()); 
  } // Generated by ComTest END
}