package liiga;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.08 12:35:18 // Generated by ComTest
 *
 */
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone39 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone39() throws CloneNotSupportedException {    // Pelaaja: 39
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("   3  |  Teemu Selänne   | Hyökkääjä"); 
    Pelaaja kopio = pelaaja.clone(); 
    assertEquals("From: Pelaaja line: 44", pelaaja.toString(), kopio.toString()); 
    pelaaja.parse("   4  |  Teemu Selänne   | Hyökkääjä"); 
    assertEquals("From: Pelaaja line: 46", false, kopio.toString().equals(pelaaja.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString83 */
  @Test
  public void testToString83() {    // Pelaaja: 83
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("   3  |  Erik Perrin   | Hyökkääjä"); 
    assertEquals("From: Pelaaja line: 86", true, pelaaja.toString().startsWith("3|Erik Perrin|Hyökkääjä|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse103 */
  @Test
  public void testParse103() {    // Pelaaja: 103
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse("   3  |  Erik Perrin   | Hyökkääjä"); 
    assertEquals("From: Pelaaja line: 106", 3, pelaaja.getPelaajaid()); 
    assertEquals("From: Pelaaja line: 107", true, pelaaja.toString().startsWith("3|Erik Perrin|Hyökkääjä|")); 
    pelaaja.rekisteroi(); 
    int n = pelaaja.getPelaajaid(); 
    pelaaja.parse(""+(n+20)); 
    pelaaja.rekisteroi(); 
    assertEquals("From: Pelaaja line: 113", n+20, pelaaja.getPelaajaid()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi149 */
  @Test
  public void testRekisteroi149() {    // Pelaaja: 149
    Pelaaja pelaaja1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 151", 0, pelaaja1.getPelaajaid()); 
    pelaaja1.rekisteroi(); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.rekisteroi(); 
    int n1 = pelaaja1.getPelaajaid(); 
    int n2 = pelaaja2.getPelaajaid(); 
    assertEquals("From: Pelaaja line: 157", n2-1, n1); 
  } // Generated by ComTest END
}